### ISSUE TITLE
add path-to-regexp support

### ISSUE THREAD

**Issue by fabienjuif** [Trampss/trampss-mst-onaction#10]
Link : https://github.com/pillarjs/path-to-regexp
Source : https://github.com/mobxjs/mobx-state-tree/issues/486#issuecomment-339965337

**Comment by fabienjuif** [comment]
Right now the code is of `take` helper is :
```
const take = (match, callback) => (action, tree) => {
  const isMatching = false
    || (isString(match) && match === action.fullpath)
    || (isFunction(match) && match(action, tree))
    || (isRegExp(match) && action.fullpath.match(match))

  if (isMatching) return callback(action, tree)
  return false
}
```

We are testing `match` type from the easiest to test to the hardest.

 - How can we test that the string is a `path` type  to apply `path-to-regexp` ?
 - Should we pass all string to `path-to-regexp` ?
     * Then what about performance ?

**Comment by fabienjuif** [comment]
FYI @wbercx @mattiamanzati

**Comment by wbercx** [comment]
Sorry for the delay.

We could benchmark the different approaches, but I doubt that passing every string to `path-to-regexp` would cause any serious bottlenecks. It would be my preferred approach.
